# CNN Model Configuration for TARDIS Emulator

model_name: "FFN_Emulator"
model_type: "FFN"

# Architecture parameters
architecture:
  input_dim: 6
  hidden_dims: [200, 200, 200, 200, 200, 200, 200]
  output_dim: 40
  activation: "mish"
  dropout_rate: "None"
